[program:nextjs]
command=yarn next dev --hostname 0.0.0.0 --port 3000
directory=/app
autostart=true
autorestart=true
environment=NODE_ENV="development"
stderr_logfile=/var/log/supervisor/nextjs.err.log
stdout_logfile=/var/log/supervisor/nextjs.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
